# host01
# host02

- hosts: host01
  name: host01 Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IF setup for vlan 10 - SVD demo
      copy: 
        src: /home/cumulus/ON-14/demo-04-host01-if
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on host01
      shell: /sbin/ifreload -a
      
- hosts: host02
  name: host02 Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IF setup for vlan 30 - SVD demo
      copy: 
        src: /home/cumulus/ON-14/demo-04-host02-if
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on host01
      shell: /sbin/ifreload -a
      
